### ISSUE TITLE
Could you explain more on the data preparation pipeline?(How to get geojson file from OSM?) much appreciated!

### ISSUE THREAD

**Issue by WanliQianKolmostar** [ni1o1/pybdshadow#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ni1o1** [comment]
- Use `osmnx.geometries.geometries_from_bbox` with `tags = {‘building’: True}` would return all building footprints in the area: 
https://osmnx.readthedocs.io/en/stable/osmnx.html#osmnx.geometries.geometries_from_bbox
Unfortunately, only a small number of buildings have a high nformation in OpenStreetMap.
- Another way to obtain building data is to purchase data from https://map.3dbuildings.com, they use AI model to predict building height.

**Comment by WanliQianKolmostar** [comment]
Will do, thanks!

**Comment by WanliQianKolmostar** [comment]
Which output method are you using for converting Geodataframe to Geojson format?

**Comment by ni1o1** [comment]
gdf.to_file("xxx.json",driver="GeoJSON")
