### ISSUE TITLE
Shadow on vertical walls

### ISSUE THREAD

**Issue by amaccarini** [ni1o1/pybdshadow#11]
Hi,
As far as I understood from the documentation, pybdshadow is currently able to calculate shadows on the ground and on the roofs of buildings. I was just wondering, is it possible to calculate shadows also on vertical walls of buildings?
For my use case, I would not need a complete shadow calculation, I would just need to know if a specific wall surface is shadowed or not (a binary output). To simplify, it would be enough to know if a single point of the wall surface (e.g. the center) is shadowed.

**Comment by Console99** [comment]
Hello，
Sorry, the part about wall shadows is a bit complicated, we haven't perfected it yet, and calculating shadows for the whole area may not get the effect you want. However, your suggestion is good and we will probably implement this feature in the future. Thank you for your question.
