### ISSUE TITLE
Shadows also before sunrise and after sunset

### ISSUE THREAD

**Issue by gcaria** [ni1o1/pybdshadow#12]
Hi,
thanks for this wonderful package, I'm really enjoying it!

I've noticed that with `pybdshadow.bdshadow_sunlight` shadow results are also provided before sunrise and after sunset for the local time, 
it seems to me there should be an error thrown in this case, since the results are not meaningful (or simply a zero area shadow provided).

I imagine this type of check is already implemented for the calculations of light/shadow daily hours on a surface.

**Comment by ni1o1** [comment]
Good idea! Thank you for your attention to our package

**Comment by gcaria** [comment]
This is something minor so probably not worth opening an issue, but I've noticed that in the docstrings it's missing the information of the unit of measurement for the `height` argument, which I assume it's meters?
